### ISSUE TITLE
Auto-generate RSS Feed from What's new on Devdocs

### ISSUE THREAD

**Issue by mhauri** [dshevtsov/whats-new-on-devdocs-from#1]
It would be great to have the what's new on Devdocs as a RSS Feed. Not sure how hard this would be to implement.

**Comment by dshevtsov** [comment]
Agree, I have it (RSS/Atom) in my backlog, but don't know when I'll have time to implement it.

**Comment by jeff-matthews** [comment]
@mhauri, this is a good idea. I was discussing RSS feeds with someone else at MMDE, but I think creating an RSS feed for the entire site might be better.

**Comment by mhauri** [comment]
@jeff-matthews I agree, it would be cool to have a RSS Feed for the whole Devdocs, but this doesn't mean we can't have one for "What's new on Devdocs" as well right :-) 

@dshevtsov glad to hear it's in your backlog, sad you haven't time to work on it. 
Sadly i'm not familiar with Ruby so I can't help either.

**Comment by jeff-matthews** [comment]
Of course not! We can still have a feed for What's new. I think the XML file that we would need to define for just the What's new would be similar to what we would need for the entire site, so it wouldn't be wasted effort.

**Comment by dshevtsov** [comment]
Testing GraphQL mutations
