### ISSUE TITLE
Add .whatsup.yml for OMS Docs site

### ISSUE THREAD

**Issue by shrielenee** [dshevtsov/whats-new-on-devdocs-from#6]
Instead of revising the `.whatsup.yml` file to use with OMS Docs (instead of DevDocs) perhaps we could have one specifically for use for OMS only.

**Comment by dshevtsov** [comment]
`.whatsup.yml` is a configuration file and it contains `magento/devdocs` as an example for a first run.
The configuration file should be ignored by git and is expected to be changed by each user of the tool for their needs. For example, my config contains 6 repositories.
I don't see a need to implement and maintain an additional example configuration for a specific repository.

But this brings me an idea of adding feature when the tool can be run for the current repo and branch like:
```
$ whatsup_github here
```
