### ISSUE TITLE
Do not report about MISSING news in the output file 

### ISSUE THREAD

**Issue by dshevtsov** [dshevtsov/whats-new-on-devdocs-from#7]
The report about missing news must go to the terminal output only.
There is no need to have it in the output file, because it will always be removed.

**UPDATE 0.2.0 version introduces separation onto 'optional' and 'required' labels. Reporting about missing news is enabled only for 'required' labels.**

**Comment by meker12** [comment]
If you want to enable automatic prepend of updated whatsnew info, then don't include the MISSING entries for Technical changes in the output at all.

Every time I re-generate after fixing descriptions, I have to remove the MISSING entries again.  I realize that one can write a script to auto-remove the MISSING Technical Changes entries, but do we need to include them?
